create table if not exists public.ai_interview_usage_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  client_ip text not null default 'unknown',
  model text not null,
  request_source text not null default 'ai-interview-demo'
);

create index if not exists idx_ai_interview_usage_logs_created_at
  on public.ai_interview_usage_logs (created_at desc);

create index if not exists idx_ai_interview_usage_logs_client_ip_created_at
  on public.ai_interview_usage_logs (client_ip, created_at desc);
