-- Bareunjari P2 Learning Layer schema draft
-- Applied to Supabase project bareunjari on 2026-08-31
-- Migration: create_p2_learning_layer

begin;

create table public.learning_candidates (
  id uuid primary key default gen_random_uuid(),
  candidate_key text not null,
  candidate_type text not null,
  scope_type text not null default 'business',
  scope_key text not null default 'bareunjari',
  title text not null,
  hypothesis text not null,
  status text not null default 'detected',
  priority text not null default 'normal',
  confidence numeric(5,4),
  detector_name text not null,
  detector_version text not null,
  detector_run_id uuid not null,
  source_brief_id bigint references public.operations_agent_briefs(id) on delete set null,
  evidence_window_start date not null,
  evidence_window_end date not null,
  first_detected_at timestamptz not null default now(),
  last_detected_at timestamptz not null default now(),
  occurrence_count integer not null default 1,
  ai_analysis_status text not null default 'pending',
  ai_analysis jsonb not null default '{}'::jsonb,
  ai_provider text,
  ai_model text,
  ai_analyzed_at timestamptz,
  review_decision text,
  review_note text,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  github_repo text,
  github_pr_number integer,
  github_pr_url text,
  promoted_path text,
  promoted_commit_sha text,
  promoted_at timestamptz,
  outcome_due_at timestamptz,
  outcome_status text not null default 'not_due',
  outcome_summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint learning_candidates_candidate_key_not_blank check (btrim(candidate_key) <> ''),
  constraint learning_candidates_candidate_type_check check (candidate_type in (
    'repeat_demand', 'usage_purpose_growth', 'repeat_customer_pattern',
    'search_to_booking_change', 'experiment_effect', 'data_quality'
  )),
  constraint learning_candidates_status_check check (status in (
    'detected', 'pending_review', 'approved', 'rejected', 'promoted',
    'monitoring', 'validated', 'invalidated', 'archived'
  )),
  constraint learning_candidates_priority_check check (priority in ('low', 'normal', 'high', 'critical')),
  constraint learning_candidates_confidence_check check (confidence is null or (confidence >= 0 and confidence <= 1)),
  constraint learning_candidates_window_check check (evidence_window_end >= evidence_window_start),
  constraint learning_candidates_occurrence_count_check check (occurrence_count > 0),
  constraint learning_candidates_ai_status_check check (ai_analysis_status in ('pending', 'completed', 'failed', 'skipped')),
  constraint learning_candidates_review_decision_check check (review_decision is null or review_decision in ('approved', 'rejected', 'needs_more_evidence')),
  constraint learning_candidates_outcome_status_check check (outcome_status in ('not_due', 'pending', 'validated', 'invalidated', 'inconclusive')),
  constraint learning_candidates_pr_number_check check (github_pr_number is null or github_pr_number > 0),
  constraint learning_candidates_detector_key_unique unique (detector_name, candidate_key)
);

create table public.learning_evidence (
  id bigint generated by default as identity primary key,
  candidate_id uuid not null references public.learning_candidates(id) on delete cascade,
  evidence_digest text not null,
  evidence_type text not null,
  source_table text not null,
  source_record_id text,
  metric_name text,
  metric_value numeric,
  comparison_value numeric,
  delta_value numeric,
  delta_percent numeric,
  sample_size integer,
  observed_at timestamptz,
  window_start date,
  window_end date,
  dimensions jsonb not null default '{}'::jsonb,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint learning_evidence_type_check check (evidence_type in ('metric', 'record', 'brief', 'experiment', 'data_quality')),
  constraint learning_evidence_sample_size_check check (sample_size is null or sample_size >= 0),
  constraint learning_evidence_window_check check (window_start is null or window_end is null or window_end >= window_start),
  constraint learning_evidence_digest_unique unique (candidate_id, evidence_digest)
);

create table public.learning_actions (
  id bigint generated by default as identity primary key,
  candidate_id uuid not null references public.learning_candidates(id) on delete cascade,
  action_type text not null,
  from_status text,
  to_status text,
  actor_type text not null,
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_label text,
  idempotency_key text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint learning_actions_type_check check (action_type in (
    'detected', 'evidence_added', 'ai_analysis', 'status_transition',
    'human_review', 'github_pr_created', 'github_pr_updated', 'kb_promoted',
    'experiment_started', 'outcome_recorded', 'archived'
  )),
  constraint learning_actions_actor_type_check check (actor_type in ('detector', 'system', 'ai', 'human', 'github')),
  constraint learning_actions_idempotency_unique unique (idempotency_key)
);

create index learning_candidates_review_queue_idx
  on public.learning_candidates (status, priority, last_detected_at desc)
  where status in ('detected', 'pending_review', 'approved');

create index learning_candidates_outcome_queue_idx
  on public.learning_candidates (outcome_status, outcome_due_at)
  where outcome_status in ('not_due', 'pending');

create index learning_candidates_source_brief_idx
  on public.learning_candidates (source_brief_id)
  where source_brief_id is not null;

create index learning_evidence_candidate_created_idx
  on public.learning_evidence (candidate_id, created_at desc);

create index learning_actions_candidate_created_idx
  on public.learning_actions (candidate_id, created_at asc);

alter table public.learning_candidates enable row level security;
alter table public.learning_evidence enable row level security;
alter table public.learning_actions enable row level security;

-- P2 v0 is backend-only. No anon/authenticated policies are created.
-- Human review should initially go through a JWT-verified Edge Function that
-- authorizes the reviewer and writes using a server-side service role client.
revoke all on table public.learning_candidates from anon, authenticated;
revoke all on table public.learning_evidence from anon, authenticated;
revoke all on table public.learning_actions from anon, authenticated;

grant select, insert, update, delete on table public.learning_candidates to service_role;
grant select, insert, update, delete on table public.learning_evidence to service_role;
grant select, insert, update, delete on table public.learning_actions to service_role;
grant usage, select on sequence public.learning_evidence_id_seq to service_role;
grant usage, select on sequence public.learning_actions_id_seq to service_role;

commit;
