create table if not exists private.reservation_message_logs (
  id bigint generated by default as identity primary key,
  reservation_id uuid not null references public.reservations(id) on delete cascade,
  reservation_number text not null,
  message_type text not null default 'access_guide',
  channel text not null default 'none',
  dry_run boolean not null default true,
  status text not null,
  dedupe_key text not null,
  usage_date date,
  code_key text,
  message_hash text,
  message_preview text,
  duplicate_blocked boolean not null default false,
  error_code text,
  actor_email text,
  created_at timestamptz not null default now()
);

create index if not exists reservation_message_logs_reservation_idx
  on private.reservation_message_logs (reservation_id, created_at desc);

create index if not exists reservation_message_logs_number_idx
  on private.reservation_message_logs (reservation_number, created_at desc);

create unique index if not exists reservation_message_logs_send_dedupe_uidx
  on private.reservation_message_logs (dedupe_key)
  where dry_run = false and status in ('queued', 'sent');

comment on table private.reservation_message_logs is
  '예약 안내 메시지 생성/발송 감사 로그. 비밀번호 평문은 저장하지 않고 마스킹된 미리보기와 해시만 저장한다.';

comment on index private.reservation_message_logs_send_dedupe_uidx is
  '실제 발송 대기/완료 로그는 dedupe_key당 하나만 허용해 중복 발송을 DB 레벨에서 차단한다.';

create or replace function public.service_reservation_message_dry_run(
  p_reservation_number text,
  p_actor_email text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_res public.reservations%rowtype;
  v_month date;
  v_code_key text;
  v_weekday_label text;
  v_secret_name text;
  v_secret_text text;
  v_codes jsonb;
  v_code text;
  v_expected_hash text;
  v_actual_hash text;
  v_message text;
  v_message_preview text;
  v_message_hash text;
  v_dedupe_key text;
  v_duplicate boolean := false;
  v_customer_ready boolean := false;
  v_status text := 'generated';
  v_error_code text := null;
  v_log_id bigint;
begin
  if p_reservation_number is null or btrim(p_reservation_number) = '' then
    raise exception 'reservation_number is required' using errcode = '22023';
  end if;

  select * into v_res
  from public.reservations
  where source = 'naver'
    and reservation_number = btrim(p_reservation_number)
  limit 1;

  if not found then
    return jsonb_build_object(
      'ok', false,
      'dryRun', true,
      'status', 'blocked_reservation_not_found',
      'errorCode', 'RESERVATION_NOT_FOUND',
      'reservationNumber', btrim(p_reservation_number)
    );
  end if;

  v_dedupe_key := 'naver:' || v_res.reservation_number || ':access_guide:v1';
  v_customer_ready := nullif(btrim(coalesce(v_res.customer_name, '')), '') is not null
    and nullif(btrim(coalesce(v_res.customer_phone, '')), '') is not null
    and nullif(btrim(coalesce(v_res.customer_email, '')), '') is not null
    and nullif(btrim(coalesce(v_res.usage_purpose, '')), '') is not null;

  if coalesce(lower(v_res.status), '') <> 'confirmed' then
    v_status := 'blocked_invalid_reservation';
    v_error_code := 'RESERVATION_NOT_CONFIRMED';
  elsif v_res.usage_date is null or v_res.start_time is null or v_res.end_time is null then
    v_status := 'blocked_invalid_reservation';
    v_error_code := 'RESERVATION_TIME_INCOMPLETE';
  elsif not v_customer_ready then
    v_status := 'blocked_customer_info';
    v_error_code := 'CUSTOMER_INFO_INCOMPLETE';
  end if;

  if v_res.usage_date is not null then
    v_month := date_trunc('month', v_res.usage_date)::date;
    v_code_key := case extract(isodow from v_res.usage_date)::int
      when 1 then 'Mon'
      when 2 then 'Tue'
      when 3 then 'Wed'
      when 4 then 'Thu'
      when 5 then 'Fri'
      when 6 then 'Sat'
      when 7 then 'Sun'
    end;
    v_weekday_label := case extract(isodow from v_res.usage_date)::int
      when 1 then '월'
      when 2 then '화'
      when 3 then '수'
      when 4 then '목'
      when 5 then '금'
      when 6 then '토'
      when 7 then '일'
    end;
  end if;

  if v_error_code is null then
    v_secret_name := 'bareunjari_door_codes_' || to_char(v_month, 'YYYY_MM');

    select decrypted_secret into v_secret_text
    from vault.decrypted_secrets
    where name = v_secret_name
    order by created_at desc
    limit 1;

    if v_secret_text is null then
      v_status := 'blocked_missing_code';
      v_error_code := 'ACCESS_CODE_VAULT_NOT_CONFIGURED';
    else
      begin
        v_codes := v_secret_text::jsonb;
      exception when others then
        v_codes := null;
      end;

      v_code := nullif(btrim(coalesce(v_codes ->> v_code_key, '')), '');
      if v_code is null or v_code !~ '^[0-9]{6}$' then
        v_status := 'blocked_missing_code';
        v_error_code := 'ACCESS_CODE_MISSING_FOR_WEEKDAY';
      else
        select code_hash into v_expected_hash
        from public.access_codes
        where access_month = v_month
          and code_key = v_code_key
        limit 1;

        v_actual_hash := encode(extensions.digest(v_code, 'sha256'), 'hex');
        if v_expected_hash is null or v_expected_hash <> v_actual_hash then
          v_status := 'blocked_missing_code';
          v_error_code := 'ACCESS_CODE_HASH_MISMATCH';
        end if;
      end if;
    end if;
  end if;

  select exists (
    select 1
    from private.reservation_message_logs
    where dedupe_key = v_dedupe_key
      and dry_run = false
      and status in ('queued', 'sent')
  ) into v_duplicate;

  if v_error_code is null and v_duplicate then
    v_status := 'blocked_duplicate';
    v_error_code := 'DUPLICATE_SEND_BLOCKED';
  end if;

  if v_error_code is null then
    v_message := format(
      '[예약 안내] 바른자리입니다.%s예약 시간 동안 편안하게 이용해 주세요.%s%s예약일: %s (%s)%s예약시간: %s ~ %s%s비밀번호: %s%s%s※ 전후 예약이 있을 수 있으니 예약 시간을 꼭 지켜주세요.%s※ 퇴실 전 정리 후 문이 잘 잠겼는지 확인해 주세요.',
      E'\n', E'\n', E'\n',
      to_char(v_res.usage_date, 'YYYY-MM-DD'), v_weekday_label, E'\n',
      to_char(v_res.start_time, 'HH24:MI'), to_char(v_res.end_time, 'HH24:MI'), E'\n',
      v_code, E'\n', E'\n', E'\n'
    );
    v_message_preview := replace(v_message, '비밀번호: ' || v_code, '비밀번호: ******');
    v_message_hash := encode(extensions.digest(v_message, 'sha256'), 'hex');
  else
    v_message_preview := format(
      '[예약 안내] 바른자리입니다.%s예약일: %s (%s)%s예약시간: %s ~ %s%s비밀번호: %s',
      E'\n',
      coalesce(to_char(v_res.usage_date, 'YYYY-MM-DD'), '-'), coalesce(v_weekday_label, '-'), E'\n',
      coalesce(to_char(v_res.start_time, 'HH24:MI'), '-'), coalesce(to_char(v_res.end_time, 'HH24:MI'), '-'), E'\n',
      case when v_error_code like 'ACCESS_CODE_%' then '[코드 설정 필요]' else '******' end
    );
  end if;

  insert into private.reservation_message_logs (
    reservation_id, reservation_number, message_type, channel, dry_run, status,
    dedupe_key, usage_date, code_key, message_hash, message_preview,
    duplicate_blocked, error_code, actor_email
  ) values (
    v_res.id, v_res.reservation_number, 'access_guide', 'none', true, v_status,
    v_dedupe_key, v_res.usage_date, v_code_key, v_message_hash, v_message_preview,
    v_duplicate, v_error_code, nullif(lower(btrim(coalesce(p_actor_email, ''))), '')
  ) returning id into v_log_id;

  return jsonb_build_object(
    'ok', v_error_code is null,
    'dryRun', true,
    'sendEnabled', false,
    'status', v_status,
    'errorCode', v_error_code,
    'logId', v_log_id,
    'reservationNumber', v_res.reservation_number,
    'reservationId', v_res.id,
    'customerReady', v_customer_ready,
    'usageDate', v_res.usage_date,
    'startTime', to_char(v_res.start_time, 'HH24:MI'),
    'endTime', to_char(v_res.end_time, 'HH24:MI'),
    'codeKey', v_code_key,
    'weekdayLabel', v_weekday_label,
    'codeConfigured', v_error_code is null or v_error_code = 'DUPLICATE_SEND_BLOCKED',
    'dedupeKey', v_dedupe_key,
    'duplicateBlocked', v_duplicate,
    'message', case when v_error_code is null then v_message else null end,
    'messagePreview', v_message_preview,
    'channelPlan', jsonb_build_array('naver_talktalk', 'sms_fallback')
  );
end;
$$;

revoke all on function public.service_reservation_message_dry_run(text, text) from public, anon, authenticated;
grant execute on function public.service_reservation_message_dry_run(text, text) to service_role;

comment on function public.service_reservation_message_dry_run(text, text) is
  '예약 전 출입 안내 dry-run. 실제 외부 발송은 수행하지 않으며 Vault 요일코드 선택, 메시지 생성, 중복검사, 감사로그 저장만 수행한다.';
