create table if not exists public.ai_interview_question_corpus (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  interview_type text not null,
  interview_type_key text not null,
  company text not null default '',
  company_key text not null default '',
  role text not null default '',
  role_key text not null default '',
  question_count smallint not null check (question_count between 1 and 10),
  questions jsonb not null,
  quality_score smallint not null default 0 check (quality_score between 0 and 100),
  model text not null,
  reuse_count integer not null default 0,
  last_used_at timestamptz not null default now()
);

create index if not exists idx_ai_interview_question_corpus_lookup
  on public.ai_interview_question_corpus (interview_type_key, company_key, role_key, question_count, quality_score desc, last_used_at desc);

create table if not exists public.ai_interview_qa_corpus (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  interview_type text not null,
  interview_type_key text not null,
  company text not null default '',
  company_key text not null default '',
  role text not null default '',
  role_key text not null default '',
  question text not null,
  answer text not null,
  answer_length integer not null default 0,
  is_english boolean not null default false
);

create index if not exists idx_ai_interview_qa_corpus_lookup
  on public.ai_interview_qa_corpus (interview_type_key, company_key, role_key, created_at desc);
